### ISSUE TITLE
Fails to read absolute file paths

### ISSUE THREAD

**Issue by lunaryorn** [Flet/semistandard#17]
`semistandard` always seems to resolves paths against the current working directory, regardless of whether they are absolute or relative, and consequently fails to read absolute file paths.  E.g.:

```
vagrant@flycheck-test:/flycheck$ semistandard --version
4.2.0
vagrant@flycheck-test:/flycheck$ semistandard test/resources/checkers/javascript-style.js
semistandard: Use Semicolons For All! (https://github.com/Flet/semistandard)
  /flycheck/test/resources/checkers/javascript-style.js:3:9: Missing space before function parentheses.
  /flycheck/test/resources/checkers/javascript-style.js:4:2: Expected indentation of 2 characters.
  /flycheck/test/resources/checkers/javascript-style.js:4:5: foo is defined but never used
  /flycheck/test/resources/checkers/javascript-style.js:4:12: Strings must use singlequote.
vagrant@flycheck-test:/flycheck$ semistandard /flycheck/test/resources/checkers/javascript-style.js
semistandard: Unexpected linter output:

Error: ENOENT, no such file or directory '/flycheck/flycheck/test/resources/checkers/javascript-style.js'
    at Object.fs.statSync (fs.js:696:18)
    at walk (/usr/lib/node_modules/semistandard/node_modules/standard-engine/node_modules/eslint/lib/util/traverse.js:36:15)
    at /usr/lib/node_modules/semistandard/node_modules/standard-engine/node_modules/eslint/lib/util/traverse.js:102:9
    at Array.forEach (native)
    at traverse (/usr/lib/node_modules/semistandard/node_modules/standard-engine/node_modules/eslint/lib/util/traverse.js:101:11)
    at CLIEngine.executeOnFiles (/usr/lib/node_modules/semistandard/node_modules/standard-engine/node_modules/eslint/lib/cli-engine.js:323:9)
    at /usr/lib/node_modules/semistandard/node_modules/standard-engine/index.js:117:56
    at zalgoSafe (/usr/lib/node_modules/semistandard/node_modules/standard-engine/node_modules/dezalgo/dezalgo.js:20:10)
    at done (/usr/lib/node_modules/semistandard/node_modules/standard-engine/node_modules/run-parallel/index.js:18:15)
    at f (/usr/lib/node_modules/semistandard/node_modules/standard-engine/node_modules/glob/node_modules/once/once.js:17:25)

If you think this is a bug in `semistandard`, open an issue: https://github.com/Flet/semistandard/issues
```

`standard` works fine.

**Comment by Flet** [comment]
Ah this was an old `standard` bug that did not get fixed in `standard-engine`... I've fixed it now!

Can you try reinstalling `semistandard` and trying again? It should pickup `standard@1.4.2` which resolves the problem.

**Comment by lunaryorn** [comment]
@Flet Will take a look tomorrow.

**Comment by lunaryorn** [comment]
@Flet Works now, thanks.
