### ISSUE TITLE
Unexpected linter output

### ISSUE THREAD

**Issue by nikmash** [Flet/semistandard#25]
I try to run semistandard and I hit this error:

```
semistandard: Unexpected linter output:

TypeError: Cannot read property 'type' of undefined
    at markPropTypesAsDeclared (/usr/local/lib/node_modules/semistandard/node_modules/eslint-plugin-react/lib/rules/prop-types.js:449:27)
    at /usr/local/lib/node_modules/semistandard/node_modules/eslint-plugin-react/lib/rules/prop-types.js:571:9
    at Array.forEach (native)
    at EventEmitter.ObjectExpression (/usr/local/lib/node_modules/semistandard/node_modules/eslint-plugin-react/lib/rules/prop-types.js:567:23)
    at EventEmitter.emit (events.js:129:20)
    at Controller.controller.traverse.enter (/usr/local/lib/node_modules/semistandard/node_modules/standard-engine/node_modules/eslint/lib/eslint.js:724:25)
    at Controller.__execute (/usr/local/lib/node_modules/semistandard/node_modules/standard-engine/node_modules/eslint/node_modules/estraverse/estraverse.js:397:31)
    at Controller.traverse (/usr/local/lib/node_modules/semistandard/node_modules/standard-engine/node_modules/eslint/node_modules/estraverse/estraverse.js:495:28)
    at EventEmitter.module.exports.api.verify (/usr/local/lib/node_modules/semistandard/node_modules/standard-engine/node_modules/eslint/lib/eslint.js:717:24)
    at processText (/usr/local/lib/node_modules/semistandard/node_modules/standard-engine/node_modules/eslint/lib/cli-engine.js:201:27)
```

It's odd because it works fine on another machine of mine. Any insight on what exactly is going on here?

**Comment by Flet** [comment]
Unsure on this, sorry. Were you able to get past this? Have you tried reinstalling the latest version?

**Comment by JGAntunes** [comment]
Same here.

```
semistandard --verbose | snazzy

semistandard: Unexpected linter output:

TypeError: Cannot read property 'type' of undefined
    at markPropTypesAsDeclared (/home/jgantunes/Documents/github/flux-app/node_modules/semistandard/node_modules/eslint-plugin-react/lib/rules/prop-types.js:450:27)
    at /home/jgantunes/Documents/github/flux-app/node_modules/semistandard/node_modules/eslint-plugin-react/lib/rules/prop-types.js:572:9
    at Array.forEach (native)
    at EventEmitter.ObjectExpression (/home/jgantunes/Documents/github/flux-app/node_modules/semistandard/node_modules/eslint-plugin-react/lib/rules/prop-types.js:568:23)
    at EventEmitter.emit (events.js:129:20)
    at Controller.controller.traverse.enter (/home/jgantunes/Documents/github/flux-app/node_modules/semistandard/node_modules/eslint/lib/eslint.js:824:25)
    at Controller.__execute (/home/jgantunes/Documents/github/flux-app/node_modules/semistandard/node_modules/eslint/node_modules/estraverse/estraverse.js:397:31)
    at Controller.traverse (/home/jgantunes/Documents/github/flux-app/node_modules/semistandard/node_modules/eslint/node_modules/estraverse/estraverse.js:495:28)
    at EventEmitter.module.exports.api.verify (/home/jgantunes/Documents/github/flux-app/node_modules/semistandard/node_modules/eslint/lib/eslint.js:817:24)
    at processText (/home/jgantunes/Documents/github/flux-app/node_modules/semistandard/node_modules/eslint/lib/cli-engine.js:199:27)
```
```
 ~/D/g/flux-app  cat node_modules/semistandard/package.json | grep version
  "version": "7.0.2",

```

**Comment by nikmash** [comment]
@Flet still hitting the error. Ended up just using eslint.

**Comment by Flet** [comment]
:(

Does `standard` blow up too?

**Comment by Flet** [comment]
Also, are you using the react plugin with eslint? May be worth trying to use it to see... Looks like the stack trace is pointing to it... `eslint-plugin-react/lib/rules/prop-types.js:450:27`

**Comment by dcousens** [comment]
@nikmash if you could try and isolate the code that would be useful.
Its likely this is a problem with 1 particular rule in eslint dying on the code you provided.

**Comment by Flet** [comment]
Closing this issue -- if you're still having issues after updating to the lastest version, feel free to open a new issue!
